### ISSUE TITLE
How does gae_config_path work?

### ISSUE THREAD

**Issue by seupedro** [zxyle/publish-gae-action#11]

**Comment by seupedro** [comment]
```yaml
 - name: Initialize Google Cloud SDK
      uses: nakassh/publish-gae-action@master
      with:
        . . .
        gae_config_path: ./folder/app.yaml 

 - name: Publish app to Google App Engine
    run: |
     . . .
      gcloud -q app deploy ./folder/app.yaml --promote
```

Is this how it is supposed to be? If not, can you provide some example how to?

**Comment by FulcronZ** [comment]
Have you checked out first before publishing? 

```
steps:
  - name: Checkout
    uses: actions/checkout@v2.3.3
  - name: Initialize Google Cloud SDK
    uses: zxyle/publish-gae-action@master
    ...
  - name: Publish app to Google App Engine
    run: |
    ...
```
