### ISSUE TITLE
ERROR: (gcloud.auth.activate-service-account) Unable to read file [client-secret.json]: [Errno 2] No such file or directory: 'client-secret.json'

### ISSUE THREAD

**Issue by SaloniSS** [zxyle/publish-gae-action#12]
#### This is the error I’m getting:

```
ERROR: (gcloud.auth.activate-service-account) Unable to read file [client-secret.json]: [Errno 2] No such file or directory: 'client-secret.json'
##[error]Process completed with exit code 1.
```

#### This is my structure:

server
|-> index.js
|-> app.yaml
|-> package.json
|-> package-lock.json

#### This is my workflow file:
```
name: Build and Deploy
on:
  push:
    branches:
      - server

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
        working-directory: ./server
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_config_path: ./server/app.yaml
      - name: Publish app to Google App Engine
        run: | 
          # This client-secret.json is converted by GCP_SA_KEY.
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote
        working-directory: ./server

```
