### ISSUE TITLE
##[error]ENOENT: no such file or directory, open './app.yaml'

### ISSUE THREAD

**Issue by yeskiy** [zxyle/publish-gae-action#13]
`##[error]ENOENT: no such file or directory, open './app.yaml' `
but this file is in the root of the project

**Comment by yeskiy** [comment]
My Workflow
```YAML
name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_variables: ${{ secrets.GAE_VARIABLES }}

      - name: Install Dependecies
        run: |
          npm install

      - name: Build
        run: npm run build

      - name: Publish app to Google App Engine
        run: |
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote
```
