### ISSUE TITLE
File `./app.yml` not found

### ISSUE THREAD

**Issue by Aloso** [zxyle/publish-gae-action#3]
I get this error:

```
##[error]ENOENT: no such file or directory, open './app.yaml'
```

The file is under `./backend/src/main/appengine/app.yml` starting from the repository root, but copying it to `./app.yml` didn't fix the issue.

Where is this file supposed to be? Could you maybe add a configuration option to specify the file path?

-----

My full workflow:

```yml
# GitHub actions

name: Deploy to App Engine (GCP)
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          # An optional variables parameter can be used
          gae_variables: ${{ secrets.GAE_VARIABLES }}

      [remaining steps omitted]
```
