### ISSUE TITLE
ENOENT: no such file or directory, open './app.yaml'

### ISSUE THREAD

**Issue by claudiuri** [zxyle/publish-gae-action#7]
My workflow
```name: Node.js CI CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Initialize Google Cloud SDK
      uses: zxyle/publish-gae-action@master
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Publish app to Google App Engine
      run: |
        # This client-secret.json is converted by GCP_SA_KEY.
        gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
        gcloud config set project ${{ secrets.PROJECT_ID }}
        gcloud -q app deploy app.yaml --promote
        # Suppose you need a cron task.
        gcloud -q app deploy cron.yaml
```
My app.yaml
![image](https://user-images.githubusercontent.com/29788908/85020869-5b40f700-b147-11ea-869e-90ef840ce47f.png)

**Comment by hishamsabur** [comment]
Have a look to this [note](https://github.com/zxyle/publish-gae-action#note)
> Use `272.0.0` Google Cloud SDK by default on GitHub-hosted runners. If you need latest version, please refer to this [action](https://github.com/GoogleCloudPlatform/github-actions/tree/master/setup-gcloud). But in most cases, this is enough.

and now use this:

```yaml
name: Publish app to Google App Engine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud -q app deploy --promote
```
Good Luck.
